services:
  web:
    build:
      context: ./azure-injury-lab
      dockerfile: Dockerfile
    env_file:
      - ./azure-injury-lab/.env
    environment:
      NGINX_ENVSUBST_FILTER: "^VISION_"

    image: azure-ml-sport-edge:latest

    container_name: azure-ml-sport-edge

    ports:
      - "80:80"

    restart: unless-stopped
